sudo: required
services:
  - docker

before_install:
  - docker build -t artemshaleyko/docker-nginx-react -f Dockerfile.dev .

script:
  - docker run -e CI=true artemshaleyko/docker-nginx-react npm run test -- --coverage