sudo: required
services:
  - docker

before_install:
  - docker build -t artemshaleyko/docker-nginx-react -f Dockerfile.dev .

script:
  - docker run -e CI=true artemshaleyko/docker-nginx-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-nginx-react"
  env: "DockerNginxReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-494257485920"
  bucket_path: "docker-nginx-react"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY